"""Shared theme tokens for prototype UI."""

COLOR_BG_MAIN = "#1E1E1E"
COLOR_SIDEBAR = "#2A0A3C"
COLOR_COVERS_BG = "#1E1E1E"
COLOR_TIMELINE_BG = "#2A2A2A"
COLOR_BOTTOM_BG = "#1E1E1E"
COLOR_CONTROLS_BG = "#1E1E1E"
COLOR_CONTROL_BTN = "#6A1B9A"

TEXT_PRIMARY = "#E0E0E0"
TEXT_MUTED = "#B8B8B8"
BG_INPUT = "#161616"
BORDER_SUBTLE = "#2A2D31"

FONT_STACK = '"Inter", "Segoe UI", "Ubuntu", sans-serif'
