"""Shared theme tokens for prototype UI."""

# Core palette (ui_ux_team/design_docs/palette.txt)
PRIMARY = "#1E90FF"
ACCENT = "#FF69B4"
BACKGROUND = "#0A0A12"
TEXT = "#E0E6ED"
SECONDARY = "#6C63FF"

COLOR_BG_MAIN = BACKGROUND
COLOR_SIDEBAR = "#1A0F2A"
COLOR_COVERS_BG = "#0E101A"
COLOR_TIMELINE_BG = "#151A28"
COLOR_BOTTOM_BG = "#0D0F18"
COLOR_CONTROLS_BG = "#0D0F18"
COLOR_CONTROL_BTN = ACCENT

TEXT_PRIMARY = TEXT
TEXT_MUTED = "#A8B3C8"
BG_INPUT = "#111624"
BORDER_SUBTLE = "#2A3550"

FONT_STACK = '"Inter", "Segoe UI", "Ubuntu", sans-serif'
